17 specify utility bounds for a power
SHADE-AI/daidepp pull request #55
Opened 2022-12-13 19:49 UTC by byung-o

PR that incorporates changes from https://github.com/SHADE-AI/daidepp/pull/34 
closes #17

2022-12-13 20:09 UTC, mjspeck requested changes

2022-12-13 20:09 UTC, mjspeck commented on src/daidepp/keywords/daide_object.py
> +_grammar = create_daide_grammar(DAIDELevel.__args__[-1], string_type="all")
```suggestion
from typing_extensions import get_args

_grammar = create_daide_grammar(get_args(DAIDELevel)[-1], string_type="all")
```

2022-12-14 13:55 UTC, mjspeck commented
Closed by #34

2022-12-14 14:02 UTC, mjspeck approved these changes

2022-12-15 17:46 UTC, Wert5 approved these changes
Looks good. I fixed an error in visit_orr (missing * in constructor). I thought there was an error in visit_not, will discuss in new issue.

2022-12-15 17:46 UTC, merged